import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const url=process.env.FEED_PAUL_URL||'http://127.0.0.1:4182/';
const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'chrome',headless:true});
const errors=[], checks=[];
const context=await browser.newContext({viewport:{width:1100,height:850},permissions:['clipboard-read','clipboard-write']});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
await page.goto(url+'?inspect');await page.evaluate(()=>document.fonts.ready);
assert.equal(await page.locator('#pick-other .who').textContent(),'The Other');
assert.match(await page.locator('footer').innerText(),/@Nicolas_chap/);
await page.locator('#pick-other').focus();await page.keyboard.press('Enter');
assert.equal(await page.locator('#pick-other').getAttribute('aria-pressed'),'true');
assert.equal(await page.evaluate(()=>feedPaul.state.phase),'menu');checks.push('Keyboard character selection does not start a round');
await page.locator('#pick-paul').click();await page.locator('#go').click();
await page.waitForTimeout(3400);assert.equal(await page.evaluate(()=>feedPaul.state.phase),'play');
let x=await page.evaluate(()=>feedPaul.state.me.x);await page.keyboard.down('ArrowRight');await page.waitForTimeout(250);await page.keyboard.up('ArrowRight');
assert.ok(await page.evaluate(()=>feedPaul.state.me.x)>x);checks.push('Keyboard movement');
await page.keyboard.press('ArrowUp');assert.equal(await page.evaluate(()=>feedPaul.state.heckles),1);
assert.ok(await page.evaluate(()=>feedPaul.state.foe.distracted)>0);
const foeX=await page.evaluate(()=>feedPaul.state.foe.x);await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>feedPaul.state.foe.x),foeX);
await page.keyboard.press('ArrowUp');assert.equal(await page.evaluate(()=>feedPaul.state.heckles),1);
assert.equal(await page.locator('#heckle').isDisabled(),true);checks.push('Up arrow heckles, briefly stops opponent and enforces cooldown');

await page.keyboard.press('p');let time=await page.evaluate(()=>feedPaul.state.timeLeft);await page.waitForTimeout(350);
assert.equal(await page.evaluate(()=>feedPaul.state.timeLeft),time);assert.equal(await page.locator('#s-pause').isVisible(),true);
await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>feedPaul.state.phase),'play');checks.push('Pause freezes simulation and keyboard resumes');
await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.equal(await page.evaluate(()=>feedPaul.state.phase),'paused');await page.locator('#resume').click();checks.push('Window blur pauses without losing the round');
assert.equal(await page.evaluate(()=>feedPaul.audio.state),'running');await page.locator('#music').click();assert.equal(await page.locator('#music').getAttribute('aria-label'),'Unmute music');await page.locator('#music').click();checks.push('Synthesized audio starts, mutes and resumes');
await page.evaluate(()=>{const f=feedPaul,s=f.state;s.me.pts=0;s.me.coh=80;s.me.briefHave=0;s.briefNeed=4;f.swallow(s.me,{kind:'overloaded',tpl:s.tplIdx},f.metrics());});
assert.deepEqual(await page.evaluate(()=>[feedPaul.state.me.pts,feedPaul.state.me.coh]),[3,75]);
await page.evaluate(()=>{const f=feedPaul;f.swallow(f.state.me,{kind:'parasite',tpl:f.state.tplIdx},f.metrics());});assert.equal(await page.evaluate(()=>feedPaul.state.me.coh),63);
assert.match(await page.locator('#legend').textContent(),/-5 cohesion/);assert.match(await page.locator('#legend').textContent(),/-12 cohesion/);checks.push('Actual scoring matches displayed penalties');
await page.evaluate(()=>{feedPaul.state.me.pts=20;feedPaul.state.me.coh=100;feedPaul.state.foe.pts=20;feedPaul.state.foe.coh=100;feedPaul.finish();});
assert.equal(await page.locator('#r-eyebrow').textContent(),'Dead heat');
const popupPromise=page.waitForEvent('popup');await page.locator('#share').click();const popup=await popupPromise;await popup.waitForLoadState('domcontentloaded').catch(()=>{});
assert.match(decodeURIComponent(popup.url()),/Dead heat/);assert.match(decodeURIComponent(popup.url()),/@Nicolas_chap/);await popup.close();checks.push('Sharing prepares a tie-aware X draft with correct handle');
await page.locator('#copy').click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'https://nickchaps.github.io/feed-paul/');
await page.locator('#again').click();assert.equal(await page.evaluate(()=>feedPaul.state.timeLeft),60);assert.equal(await page.evaluate(()=>feedPaul.state.grace),0);checks.push('Replay resets round and template grace');
await page.reload();assert.equal(await page.evaluate(()=>feedPaul.state.best),20);checks.push('Best score persists');
await page.screenshot({path:'output/playwright/desktop-menu.png'});
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});mobile.on('pageerror',e=>errors.push(e.message));
await mobile.goto(url+'?inspect');await mobile.screenshot({path:'output/playwright/mobile-menu.png'});
assert.ok(await mobile.locator('#go').isVisible());assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await mobile.locator('#go').tap();await mobile.waitForTimeout(3400);const box=await mobile.locator('#cv').boundingBox();await mobile.touchscreen.tap(box.x+box.width*.8,box.y+box.height*.65);await mobile.waitForTimeout(300);
assert.ok(await mobile.evaluate(()=>feedPaul.state.me.x/feedPaul.state.W)>.7);await mobile.screenshot({path:'output/playwright/mobile-game.png'});await mobile.locator('#heckle').tap();assert.equal(await mobile.evaluate(()=>feedPaul.state.heckles),1);checks.push('Mobile touch movement, heckle, menu fit and no horizontal overflow');
await mobile.close();await page.reload();await page.locator('#go').click();
await page.evaluate(()=>{window.auto=setInterval(()=>{if(feedPaul.state.phase==='play')feedPaul.steer();},60);});
// A full round, including all template changes and the final scoreboard.
await page.waitForFunction(()=>feedPaul.state.phase==='over',{},{timeout:75000});
assert.ok(await page.evaluate(()=>feedPaul.state.me.pts)>0);assert.equal(await page.evaluate(()=>feedPaul.state.timeLeft),0);checks.push('Real 60-second round completes, scores and renders results');
await page.screenshot({path:'output/playwright/results.png'});assert.deepEqual(errors,[]);
const result={url,checks,errors,score:await page.locator('#r-breakdown').innerText()};await fs.writeFile('output/playwright/verification.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();
